"""add_invoice_template_to_users

Revision ID: 214e19b5d17e
Revises: cdaac9e11ead
Create Date: 2026-06-04 07:49:09.925375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214e19b5d17e'
down_revision: Union[str, Sequence[str], None] = 'cdaac9e11ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invoice_template', sa.String(), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invoice_template')
    # ### end Alembic commands ###
