"""password_largebinary

Revision ID: 41e7ad0d2cea
Revises: e787c4f53805
Create Date: 2026-05-30 07:55:49.142203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e7ad0d2cea'
down_revision: Union[str, Sequence[str], None] = 'e787c4f53805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE users ALTER COLUMN password TYPE BYTEA USING password::bytea")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
