"""add_siren_to_clients

Revision ID: 77d77360b2f6
Revises: 41e7ad0d2cea
Create Date: 2026-05-30 14:50:39.786082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d77360b2f6'
down_revision: Union[str, Sequence[str], None] = '41e7ad0d2cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('siren', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'siren')
    # ### end Alembic commands ###
