"""add_category_to_payments

Revision ID: c878f1cecdb4
Revises: 214e19b5d17e
Create Date: 2026-06-07 14:38:57.274352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c878f1cecdb4'
down_revision: Union[str, Sequence[str], None] = '214e19b5d17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'category')
    # ### end Alembic commands ###
