"""add_payment_categories_to_users

Revision ID: cabb7a24e6e7
Revises: c878f1cecdb4
Create Date: 2026-06-07 15:01:15.847466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabb7a24e6e7'
down_revision: Union[str, Sequence[str], None] = 'c878f1cecdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_categories')
    # ### end Alembic commands ###
