"""add_name_to_clients

Revision ID: cdaac9e11ead
Revises: 77d77360b2f6
Create Date: 2026-06-01 10:49:35.549743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdaac9e11ead'
down_revision: Union[str, Sequence[str], None] = '77d77360b2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ajoute la colonne nullable d'abord
    op.add_column('clients', sa.Column('name', sa.String(), nullable=True))
    
    # Copie company_name si présent, sinon contact_name
    op.execute("""
        UPDATE clients
        SET name = COALESCE(NULLIF(company_name, ''), contact_name)
    """)
    
    # Passe la colonne en NOT NULL
    op.alter_column('clients', 'name', nullable=False)
    
    op.alter_column('clients', 'contact_name',
               existing_type=sa.VARCHAR(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'contact_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
